window.NINJA_DATA = {
  talents: [
    {
      name: 'Eye of Mirror',
      type: 'Extreme',
      emblemOnly: false,
      passiveStats: {
        Other: {
          value: null,
          unit: 'text',
          display: '15% chance to copy jutsu, 20% chance genjutsu rebound',
        },
      },
      images: [
        'assets/eye-of-mirror-1.webp',
        'assets/eye-of-mirror-2.webp',
        'assets/eye-of-mirror-3.webp',
        'assets/eye-of-mirror-4.webp',
        'assets/eye-of-mirror-5.webp',
        'assets/eye-of-mirror-6.webp',
      ],
      aliases: ['EoM'],
      index: 1,
    },
    {
      name: 'Eight Extremities',
      type: 'Extreme',
      emblemOnly: false,
      passiveStats: {
        'Max HP': { value: 10.0, unit: '%', display: '10%' },
        Agility: { value: 20.0, unit: '%', display: '20%' },
        'Dmg. Bonus': { value: 20.0, unit: '%', display: '20% taijutsu' },
      },
      images: [
        'assets/8ex-1.webp',
        'assets/8ex-2.webp',
        'assets/8ex-3.webp',
        'assets/8ex-4.webp',
        'assets/8ex-5.webp',
        'assets/8ex-6.webp',
      ],
      aliases: ['8ex'],
      index: 2,
    },
    {
      name: 'Dark Eye',
      type: 'Extreme',
      emblemOnly: false,
      passiveStats: {
        'Max CP': { value: 20.0, unit: '%', display: '20%' },
        'Crit chance%': { value: 5.0, unit: '%', display: '5%' },
        'Crit dmg%': { value: 10.0, unit: '%', display: '10%' },
        Dodge: { value: 10.0, unit: '%', display: '10%' },
        Accuracy: { value: 10.0, unit: '%', display: '10%' },
        Other: { value: null, unit: 'text', display: '25% extra CP per charge' },
      },
      images: [
        'assets/dark-eye-1.webp',
        'assets/dark-eye-2.webp',
        'assets/dark-eye-3.webp',
        'assets/dark-eye-4.webp',
        'assets/dark-eye-5.webp',
        'assets/dark-eye-6.webp',
      ],
      aliases: [],
      index: 3,
    },
    {
      name: 'Deadly Performance',
      type: 'Extreme',
      emblemOnly: false,
      passiveStats: {
        'Dmg. Reduction': { value: 5.0, unit: '%', display: '5%' },
        Other: {
          value: null,
          unit: 'text',
          display: '20% stun resist, 19% chance to  rebound 50% dmg taken',
        },
      },
      images: [
        'assets/deadly-performance-1.webp',
        'assets/deadly-performance-2.webp',
        'assets/deadly-performance-3.webp',
        'assets/deadly-performance-4.webp',
        'assets/deadly-performance-5.webp',
        'assets/deadly-performance-6.webp',
      ],
      aliases: [],
      index: 4,
    },
    {
      name: "Orochi's Rage",
      type: 'Extreme',
      emblemOnly: false,
      passiveStats: {
        'Dmg. Reduction': { value: 10.0, unit: '%', display: '10%' },
        'HP regen': { value: 4.0, unit: '%', display: '4% when HP <50%' },
        Other: {
          value: null,
          unit: 'text',
          display: 'poison immunity, 20% chance to  HP recover 60% dmg',
        },
      },
      images: [
        'assets/orochi-s-rage-1.webp',
        'assets/orochi-s-rage-2.webp',
        'assets/orochi-s-rage-3.webp',
        'assets/orochi-s-rage-4.webp',
        'assets/orochi-s-rage-5.webp',
        'assets/orochi-s-rage-6.webp',
      ],
      aliases: [],
      index: 5,
    },
    {
      name: 'Saint Power',
      type: 'Extreme',
      emblemOnly: false,
      passiveStats: {
        'Max HP': { value: 800.0, unit: 'flat', display: '800' },
        'HP regen': { value: '220, 200', unit: 'text', display: '220 + 200 when HP <70%' },
        Other: { value: null, unit: 'text', display: 'Unyielding' },
      },
      images: [
        'assets/saint-power-1.webp',
        'assets/saint-power-2.webp',
        'assets/saint-power-3.webp',
        'assets/saint-power-4.webp',
        'assets/saint-power-5.webp',
        'assets/saint-power-6.webp',
      ],
      aliases: [],
      index: 6,
    },
    {
      name: 'Insect Symbiosis',
      type: 'Extreme',
      emblemOnly: false,
      passiveStats: {
        'Max HP': { value: 10.0, unit: '%', display: '10% of CP' },
        Purify: { value: 1.0, unit: '%', display: '1%/700 CP' },
        'Dmg. Bonus': { value: 10.0, unit: '%', display: '10% of CP' },
        'Dmg. Reduction': { value: 10.0, unit: '%', display: '10%' },
        'CP regen': { value: 6.0, unit: '%', display: '6% when CP <50%' },
        Other: {
          value: null,
          unit: 'text',
          display: '50% chance to 650 HP recover with CP drains/reductions',
        },
      },
      images: [
        'assets/insect-symbiosis-1.webp',
        'assets/insect-symbiosis-2.webp',
        'assets/insect-symbiosis-3.webp',
        'assets/insect-symbiosis-4.webp',
        'assets/insect-symbiosis-5.webp',
        'assets/insect-symbiosis-6.webp',
      ],
      aliases: [],
      index: 7,
    },
    {
      name: 'Soul Marionette',
      type: 'Extreme',
      emblemOnly: true,
      passiveStats: {
        Purify: { value: 1.0, unit: '%', display: '1%/700 HP' },
        'Dmg. Bonus': { value: 10.0, unit: '%', display: '10%' },
        Other: {
          value: null,
          unit: 'text',
          display: '50% chance to inflict chaos when target is poisoned and 650 HP recover',
        },
      },
      images: [
        'assets/soul-marionette-1.webp',
        'assets/soul-marionette-2.webp',
        'assets/soul-marionette-3.webp',
        'assets/soul-marionette-4.webp',
        'assets/soul-marionette-5.webp',
        'assets/soul-marionette-6.webp',
      ],
      aliases: [],
      index: 8,
    },
    {
      name: 'Eye of Creation',
      type: 'Extreme',
      emblemOnly: true,
      passiveStats: {
        'Max CP': { value: 15.0, unit: '%', display: '15%' },
        Purify: { value: 15.0, unit: '%', display: '15%' },
        Other: {
          value: null,
          unit: 'text',
          display:
            '45% chance to use jutsu without CP**, 25% chance to reduce CD in half; **convert 100% CP cost to dmg',
        },
      },
      images: [
        'assets/eye-of-creation-1.webp',
        'assets/eye-of-creation-2.webp',
        'assets/eye-of-creation-3.webp',
        'assets/eye-of-creation-4.webp',
        'assets/eye-of-creation-5.webp',
        'assets/eye-of-creation-6.webp',
      ],
      aliases: [],
      index: 9,
    },
    {
      name: 'Knowledge of Time',
      type: 'Extreme',
      emblemOnly: true,
      passiveStats: {
        Agility: { value: 2.0, unit: 'flat', display: '2/500 HP' },
        'Dmg. Bonus': { value: 1.0, unit: '%', display: '1%/12 Agility' },
      },
      images: [
        'assets/knowledge-of-time-1.webp',
        'assets/knowledge-of-time-2.webp',
        'assets/knowledge-of-time-3.webp',
        'assets/knowledge-of-time-4.webp',
        'assets/knowledge-of-time-5.webp',
        'assets/knowledge-of-time-6.webp',
      ],
      aliases: [],
      index: 10,
    },
    {
      name: 'Byakugan',
      type: 'Extreme',
      emblemOnly: false,
      passiveStats: {
        'Crit chance%': { value: 10.0, unit: '%', display: '10%' },
        Accuracy: { value: 25.0, unit: '%', display: '25%' },
      },
      images: [
        'assets/byakugan-1.webp',
        'assets/byakugan-2.webp',
        'assets/byakugan-3.webp',
        'assets/byakugan-4.webp',
        'assets/byakugan-5.webp',
        'assets/byakugan-6.webp',
      ],
      aliases: [],
      index: 11,
    },
    {
      name: 'Sharingan',
      type: 'Extreme',
      emblemOnly: false,
      passiveStats: {
        Agility: { value: 15.0, unit: 'flat', display: '15' },
        Dodge: { value: 10.0, unit: '%', display: '10%' },
        Accuracy: { value: 15.0, unit: '%', display: '15%' },
      },
      images: [
        'assets/sharingan-1.webp',
        'assets/sharingan-2.webp',
        'assets/sharingan-3.webp',
        'assets/sharingan-4.webp',
        'assets/sharingan-5.webp',
        'assets/sharingan-6.webp',
      ],
      aliases: [],
      index: 12,
    },
    {
      name: 'Super Beast Scroll',
      type: 'Extreme',
      emblemOnly: false,
      passiveStats: {
        'Max HP': { value: 10.0, unit: '%', display: '10%' },
        'Max CP': { value: 30.0, unit: '%', display: '30%' },
      },
      images: [
        'assets/super-beast-scroll-1.webp',
        'assets/super-beast-scroll-2.webp',
        'assets/super-beast-scroll-3.webp',
        'assets/super-beast-scroll-4.webp',
        'assets/super-beast-scroll-5.webp',
        'assets/super-beast-scroll-6.webp',
      ],
      aliases: [],
      index: 13,
    },
    {
      name: 'Paper',
      type: 'Extreme',
      emblemOnly: false,
      passiveStats: {
        Agility: { value: 10.0, unit: 'flat', display: '10' },
        Dodge: { value: 15.0, unit: '%', display: '15%' },
        Accuracy: { value: 15.0, unit: '%', display: '15%' },
      },
      images: [
        'assets/paper-1.webp',
        'assets/paper-2.webp',
        'assets/paper-3.webp',
        'assets/paper-4.webp',
        'assets/paper-5.webp',
        'assets/paper-6.webp',
      ],
      aliases: [],
      index: 14,
    },
    {
      name: 'Magma',
      type: 'Extreme',
      emblemOnly: false,
      passiveStats: {
        'Max HP': { value: 10.0, unit: '%', display: '10%' },
        Accuracy: { value: 15.0, unit: '%', display: '15%' },
        Other: { value: null, unit: 'text', display: '30% chance to inflict blaze 3%' },
      },
      images: [
        'assets/magma-1.webp',
        'assets/magma-2.webp',
        'assets/magma-3.webp',
        'assets/magma-4.webp',
        'assets/magma-5.webp',
        'assets/magma-6.webp',
      ],
      aliases: [],
      index: 15,
    },
    {
      name: 'Glint',
      type: 'Extreme',
      emblemOnly: false,
      passiveStats: {
        Agility: { value: 20.0, unit: 'flat', display: '20' },
        Accuracy: { value: 15.0, unit: '%', display: '15%' },
      },
      images: [
        'assets/glint-1.webp',
        'assets/glint-2.webp',
        'assets/glint-3.webp',
        'assets/glint-4.webp',
        'assets/glint-5.webp',
        'assets/glint-6.webp',
      ],
      aliases: [],
      index: 16,
    },
    {
      name: 'Karma',
      type: 'Extreme',
      emblemOnly: false,
      passiveStats: {
        'Max HP': { value: 10.0, unit: '%', display: '10%' },
        Other: { value: null, unit: 'text', display: '30% chance to use jutsu without CP' },
      },
      images: [
        'assets/karma-1.webp',
        'assets/karma-2.webp',
        'assets/karma-3.webp',
        'assets/karma-4.webp',
        'assets/karma-5.webp',
        'assets/karma-6.webp',
      ],
      aliases: [],
      index: 17,
    },
    {
      name: 'Shinigami',
      type: 'Extreme',
      emblemOnly: false,
      passiveStats: {
        'Dmg. Reduction': { value: 15.0, unit: '%', display: '15%' },
        Other: { value: null, unit: 'text', display: '12% debuff resist' },
      },
      images: [
        'assets/shinigami-1.webp',
        'assets/shinigami-2.webp',
        'assets/shinigami-3.webp',
        'assets/shinigami-4.webp',
        'assets/shinigami-5.webp',
        'assets/shinigami-6.webp',
      ],
      aliases: [],
      index: 18,
    },
    {
      name: 'Magnetic Sand',
      type: 'Extreme',
      emblemOnly: false,
      passiveStats: {
        'Crit chance%': { value: 10.0, unit: '%', display: '10%' },
        Accuracy: { value: 20.0, unit: '%', display: '20%' },
      },
      images: [
        'assets/magnetic-sand-1.webp',
        'assets/magnetic-sand-2.webp',
        'assets/magnetic-sand-3.webp',
        'assets/magnetic-sand-4.webp',
        'assets/magnetic-sand-5.webp',
        'assets/magnetic-sand-6.webp',
      ],
      aliases: [],
      index: 19,
    },
    {
      name: 'Sand Manipulation',
      type: 'Extreme',
      emblemOnly: false,
      passiveStats: {
        'Max HP': { value: 10.0, unit: '%', display: '10%' },
        'Dmg. Reduction': { value: 10.0, unit: '%', display: '10%' },
        'HP regen': { value: 100.0, unit: 'flat', display: '100' },
      },
      images: [
        'assets/sand-manipulation-1.webp',
        'assets/sand-manipulation-2.webp',
        'assets/sand-manipulation-3.webp',
        'assets/sand-manipulation-4.webp',
        'assets/sand-manipulation-5.webp',
        'assets/sand-manipulation-6.webp',
      ],
      aliases: [],
      index: 20,
    },
    {
      name: 'Butterfly Vein',
      type: 'Extreme',
      emblemOnly: false,
      passiveStats: {
        'Max HP': { value: 10.0, unit: '%', display: '10%' },
        'Max CP': { value: 10.0, unit: '%', display: '10%' },
        'HP regen': { value: 375.0, unit: 'flat', display: '375' },
      },
      images: [
        'assets/butterfly-vein-1.webp',
        'assets/butterfly-vein-2.webp',
        'assets/butterfly-vein-3.webp',
        'assets/butterfly-vein-4.webp',
        'assets/butterfly-vein-5.webp',
        'assets/butterfly-vein-6.webp',
      ],
      aliases: [],
      index: 21,
    },
    {
      name: 'Jogan',
      type: 'Extreme',
      emblemOnly: false,
      passiveStats: {
        Agility: { value: 10.0, unit: 'flat', display: '10' },
        Accuracy: { value: 20.0, unit: '%', display: '20%' },
        Other: { value: null, unit: 'text', display: 'CP recover 30% dmg taken' },
      },
      images: [
        'assets/jogan-1.webp',
        'assets/jogan-2.webp',
        'assets/jogan-3.webp',
        'assets/jogan-4.webp',
        'assets/jogan-5.webp',
        'assets/jogan-6.webp',
      ],
      aliases: [],
      index: 22,
    },
    {
      name: 'Ice Kenjutsu',
      type: 'Extreme',
      emblemOnly: false,
      passiveStats: {
        Accuracy: { value: 15.0, unit: '%', display: '15%' },
        Purify: { value: 15.0, unit: '%', display: '15%' },
        Other: { value: null, unit: 'text', display: '15% chance to use jutsu without CP' },
      },
      images: [
        'assets/ice-kenjutsu-1.webp',
        'assets/ice-kenjutsu-2.webp',
        'assets/ice-kenjutsu-3.webp',
        'assets/ice-kenjutsu-4.webp',
        'assets/ice-kenjutsu-5.webp',
        'assets/ice-kenjutsu-6.webp',
      ],
      aliases: [],
      index: 23,
    },
    {
      name: 'Wood Control',
      type: 'Extreme',
      emblemOnly: false,
      passiveStats: {
        'Max HP': { value: 15.0, unit: '%', display: '15%' },
        Accuracy: { value: 20.0, unit: '%', display: '20%' },
        'HP regen': { value: 300.0, unit: 'flat', display: '300' },
        Other: { value: null, unit: 'text', display: '20% debuff resist' },
      },
      images: [
        'assets/wood-control-1.webp',
        'assets/wood-control-2.webp',
        'assets/wood-control-3.webp',
        'assets/wood-control-4.webp',
        'assets/wood-control-5.webp',
        'assets/wood-control-6.webp',
      ],
      aliases: [],
      index: 24,
    },
    {
      name: 'Rinner Sharingan',
      type: 'Extreme',
      emblemOnly: false,
      passiveStats: {
        'Max CP': { value: 12.0, unit: '%', display: '12%' },
        Accuracy: { value: 25.0, unit: '%', display: '25%' },
        'CP regen': { value: 250, unit: 'flat', display: '250' },
        Other: { value: null, unit: 'text', display: 'CP recover 10% dmg taken' },
      },
      images: [
        'assets/rinner-sharingan-1.webp',
        'assets/rinner-sharingan-2.webp',
        'assets/rinner-sharingan-3.webp',
        'assets/rinner-sharingan-4.webp',
        'assets/rinner-sharingan-5.webp',
        'assets/rinner-sharingan-6.webp',
      ],
      aliases: [],
      index: 25,
    },
    {
      name: 'Rinnegan',
      type: 'Extreme',
      emblemOnly: false,
      passiveStats: {
        'Max HP': { value: 10.0, unit: '%', display: '10%' },
        'Max CP': { value: 10.0, unit: '%', display: '10%' },
        Agility: { value: 8.0, unit: 'flat', display: '8' },
        Accuracy: { value: 15.0, unit: '%', display: '15%' },
        'Dmg. Bonus': { value: 10.0, unit: '%', display: '10%' },
      },
      images: [
        'assets/rinnegan-1.webp',
        'assets/rinnegan-2.webp',
        'assets/rinnegan-3.webp',
        'assets/rinnegan-4.webp',
        'assets/rinnegan-5.webp',
        'assets/rinnegan-6.webp',
      ],
      aliases: [],
      index: 26,
    },
    {
      name: 'Shadow Control',
      type: 'Extreme',
      emblemOnly: false,
      passiveStats: {
        'Max CP': { value: 800.0, unit: 'flat', display: '800' },
        Agility: { value: 18.0, unit: 'flat', display: '18' },
        Accuracy: { value: 12.0, unit: '%', display: '12%' },
      },
      images: [
        'assets/shadow-control-1.webp',
        'assets/shadow-control-2.webp',
        'assets/shadow-control-3.webp',
        'assets/shadow-control-4.webp',
        'assets/shadow-control-5.webp',
        'assets/shadow-control-6.webp',
      ],
      aliases: [],
      index: 27,
    },
    {
      name: 'Hakaiken',
      type: 'Extreme',
      emblemOnly: false,
      passiveStats: {
        Agility: { value: 12.0, unit: 'flat', display: '12' },
        'Dmg. Bonus': { value: 50, unit: '%', display: '50% taijutsu' },
      },
      images: [
        'assets/hakaiken-1.webp',
        'assets/hakaiken-2.webp',
        'assets/hakaiken-3.webp',
        'assets/hakaiken-4.webp',
        'assets/hakaiken-5.webp',
        'assets/hakaiken-6.webp',
      ],
      aliases: [],
      index: 28,
    },
    {
      name: 'Dark Devil Beast',
      type: 'Extreme',
      emblemOnly: false,
      passiveStats: {
        Agility: { value: 12.0, unit: 'flat', display: '12' },
        Accuracy: { value: 25.0, unit: '%', display: '25%' },
      },
      images: [
        'assets/ddb-1.webp',
        'assets/ddb-2.webp',
        'assets/ddb-3.webp',
        'assets/ddb-4.webp',
        'assets/ddb-5.webp',
        'assets/ddb-6.webp',
      ],
      aliases: ['DDB'],
      index: 29,
    },
    {
      name: 'Dragon Force',
      type: 'Extreme',
      emblemOnly: false,
      passiveStats: {
        'Dmg. Bonus': { value: 15.0, unit: '%', display: '15%' },
        'Dmg. Reduction': { value: 12.0, unit: '%', display: '12%' },
        Other: { value: null, unit: 'text', display: '5% debuff resist' },
      },
      images: [
        'assets/dragon-force-1.webp',
        'assets/dragon-force-2.webp',
        'assets/dragon-force-3.webp',
        'assets/dragon-force-4.webp',
        'assets/dragon-force-5.webp',
        'assets/dragon-force-6.webp',
      ],
      aliases: [],
      index: 30,
    },
    {
      name: 'Mist Force',
      type: 'Extreme',
      emblemOnly: false,
      passiveStats: {
        'Max CP': { value: 10.0, unit: '%', display: '10%' },
        Purify: { value: 10.0, unit: '%', display: '10%' },
        'Dmg. Reduction': { value: 10.0, unit: '%', display: '10%' },
        Other: { value: null, unit: 'text', display: '10% debuff resist' },
      },
      images: [
        'assets/mist-force-1.webp',
        'assets/mist-force-2.webp',
        'assets/mist-force-3.webp',
        'assets/mist-force-4.webp',
        'assets/mist-force-5.webp',
        'assets/mist-force-6.webp',
      ],
      aliases: [],
      index: 31,
    },
    {
      name: 'Soul General Swiftness',
      type: 'Extreme',
      emblemOnly: false,
      passiveStats: {
        Agility: { value: 10.0, unit: 'flat', display: '10' },
        'Crit chance%': { value: 10.0, unit: '%', display: '10%' },
        Accuracy: { value: 10.0, unit: '%', display: '10%' },
        Other: { value: null, unit: 'text', display: '50% increase weapon damage and accuracy' },
      },
      images: [
        'assets/soul-general-swiftness-1.webp',
        'assets/soul-general-swiftness-2.webp',
        'assets/soul-general-swiftness-3.webp',
        'assets/soul-general-swiftness-4.webp',
        'assets/soul-general-swiftness-5.webp',
        'assets/soul-general-swiftness-6.webp',
      ],
      aliases: [],
      index: 32,
    },
    {
      name: 'Insect Control',
      type: 'Extreme',
      emblemOnly: false,
      passiveStats: {
        'Max CP': { value: 1000.0, unit: 'flat', display: '1000' },
        Purify: { value: 10.0, unit: '%', display: '10%' },
        Other: { value: null, unit: 'text', display: '8% chance to use jutsu without CP' },
      },
      images: [
        'assets/insect-control-1.webp',
        'assets/insect-control-2.webp',
        'assets/insect-control-3.webp',
        'assets/insect-control-4.webp',
        'assets/insect-control-5.webp',
        'assets/insect-control-6.webp',
      ],
      aliases: [],
      index: 33,
    },
    {
      name: 'Art Style: Clay',
      type: 'Extreme',
      emblemOnly: false,
      passiveStats: {
        'Crit chance%': { value: 10.0, unit: '%', display: '10%' },
        'Crit dmg%': { value: 10.0, unit: '%', display: '10%' },
        'Dmg. Bonus': { value: 10.0, unit: '%', display: '10%' },
      },
      images: [
        'assets/clay-1.webp',
        'assets/clay-2.webp',
        'assets/clay-3.webp',
        'assets/clay-4.webp',
        'assets/clay-5.webp',
        'assets/clay-6.webp',
      ],
      aliases: ['Clay'],
      index: 34,
    },
    {
      name: 'Infinity',
      type: 'Extreme',
      emblemOnly: false,
      passiveStats: {
        'Max HP': { value: 10.0, unit: '%', display: '10%' },
        'Max CP': { value: 10.0, unit: '%', display: '10%' },
        Agility: { value: 10.0, unit: 'flat', display: '10' },
        Other: { value: null, unit: 'text', display: '10% debuff rebound' },
      },
      images: [
        'assets/infinity-1.webp',
        'assets/infinity-2.webp',
        'assets/infinity-3.webp',
        'assets/infinity-4.webp',
        'assets/infinity-5.webp',
        'assets/infinity-6.webp',
      ],
      aliases: [],
      index: 35,
    },
    {
      name: 'Underworld',
      type: 'Extreme',
      emblemOnly: false,
      passiveStats: {
        Accuracy: { value: 25.0, unit: '%', display: '25%' },
        Other: { value: null, unit: 'text', display: '10% dmg rebound' },
      },
      images: [
        'assets/underworld-1.webp',
        'assets/underworld-2.webp',
        'assets/underworld-3.webp',
        'assets/underworld-4.webp',
        'assets/underworld-5.webp',
        'assets/underworld-6.webp',
      ],
      aliases: [],
      index: 36,
    },
    {
      name: 'Cataclysm',
      type: 'Extreme',
      emblemOnly: false,
      passiveStats: {
        Other: {
          value: null,
          unit: 'text',
          display:
            '20% chance to steal buff with weapon attack, 25% chance to  inflict blind and numb',
        },
      },
      images: [
        'assets/cataclysm-1.webp',
        'assets/cataclysm-2.webp',
        'assets/cataclysm-3.webp',
        'assets/cataclysm-4.webp',
        'assets/cataclysm-5.webp',
        'assets/cataclysm-6.webp',
      ],
      aliases: [],
      index: 37,
    },
    {
      name: 'Demon Sound',
      type: 'Secret',
      emblemOnly: false,
      passiveStats: {
        Other: { value: null, unit: 'text', display: '70% chance to inflict weaken 32%' },
      },
      images: [
        'assets/demon-sound-1.webp',
        'assets/demon-sound-2.webp',
        'assets/demon-sound-3.webp',
      ],
      aliases: [],
      index: 38,
    },
    {
      name: 'Enraged Forest',
      type: 'Secret',
      emblemOnly: false,
      passiveStats: {
        Other: {
          value: null,
          unit: 'text',
          display: '58% chance to 6% HP and CP recover when using water and earth skills',
        },
      },
      images: [
        'assets/enraged-forest-1.webp',
        'assets/enraged-forest-2.webp',
        'assets/enraged-forest-3.webp',
      ],
      aliases: [],
      index: 39,
    },
    {
      name: 'Explosive Lava',
      type: 'Secret',
      emblemOnly: false,
      passiveStats: {
        'Dmg. Bonus': { value: null, unit: 'text', display: '10% fire & earth ninjutsu' },
      },
      images: [
        'assets/explosive-lava-1.webp',
        'assets/explosive-lava-2.webp',
        'assets/explosive-lava-3.webp',
      ],
      aliases: [],
      index: 40,
    },
    {
      name: 'Hidden Silhouette',
      type: 'Secret',
      emblemOnly: false,
      passiveStats: {
        Other: { value: null, unit: 'text', display: '15% chance to inflict capture 10%' },
      },
      images: [
        'assets/hidden-silhouette-1.webp',
        'assets/hidden-silhouette-2.webp',
        'assets/hidden-silhouette-3.webp',
      ],
      aliases: [],
      index: 41,
    },
    {
      name: 'Icy Crystal',
      type: 'Secret',
      emblemOnly: false,
      passiveStats: {
        Other: { value: null, unit: 'text', display: '13% chance to inflict frozen' },
      },
      images: [
        'assets/ice-crystal-1.webp',
        'assets/ice-crystal-2.webp',
        'assets/ice-crystal-3.webp',
      ],
      aliases: [],
      index: 42,
    },
    {
      name: 'Iron Sand',
      type: 'Secret',
      emblemOnly: true,
      passiveStats: {
        Other: {
          value: null,
          unit: 'text',
          display: '15% chance to gain protection 100% for next turn when receiving 1000 damage',
        },
      },
      images: ['assets/iron-sand-1.webp', 'assets/iron-sand-2.webp', 'assets/iron-sand-3.webp'],
      aliases: [],
      index: 43,
    },
    {
      name: 'Crystal Manifestation',
      type: 'Secret',
      emblemOnly: false,
      passiveStats: { Other: { value: null, unit: 'text', display: '10% debuff resist' } },
      images: [
        'assets/crystal-manifestation-1.webp',
        'assets/crystal-manifestation-2.webp',
        'assets/crystal-manifestation-3.webp',
      ],
      aliases: [],
      index: 44,
    },
    {
      name: 'Light Matter',
      type: 'Secret',
      emblemOnly: false,
      passiveStats: {
        Other: { value: null, unit: 'text', display: '10% chance to inflict internal injury' },
      },
      images: [
        'assets/light-matter-1.webp',
        'assets/light-matter-2.webp',
        'assets/light-matter-3.webp',
      ],
      aliases: [],
      index: 45,
    },
    {
      name: 'Dark Matter',
      type: 'Secret',
      emblemOnly: false,
      passiveStats: {
        Other: { value: null, unit: 'text', display: '10% chance to disable weapon' },
      },
      images: [
        'assets/dark-matter-1.webp',
        'assets/dark-matter-2.webp',
        'assets/dark-matter-3.webp',
      ],
      aliases: [],
      index: 46,
    },
    {
      name: 'Lunar Fang',
      type: 'Secret',
      emblemOnly: false,
      passiveStats: { 'Dmg. Bonus': { value: 15.0, unit: '%', display: '15%' } },
      images: ['assets/lunar-fang-1.webp', 'assets/lunar-fang-2.webp', 'assets/lunar-fang-3.webp'],
      aliases: [],
      index: 47,
    },
    {
      name: 'Lightning Infusion',
      type: 'Secret',
      emblemOnly: false,
      passiveStats: { 'Crit dmg%': { value: 20.0, unit: '%', display: '20%' } },
      images: [
        'assets/lightning-infusion-1.webp',
        'assets/lightning-infusion-2.webp',
        'assets/lightning-infusion-3.webp',
      ],
      aliases: [],
      index: 48,
    },
    {
      name: 'Black Thunder',
      type: 'Secret',
      emblemOnly: false,
      passiveStats: { 'Crit dmg%': { value: 15.0, unit: '%', display: '15%' } },
      images: [
        'assets/black-thunder-1.webp',
        'assets/black-thunder-2.webp',
        'assets/black-thunder-3.webp',
      ],
      aliases: [],
      index: 49,
    },
    {
      name: 'Snowstorm',
      type: 'Secret',
      emblemOnly: false,
      passiveStats: {
        Other: { value: null, unit: 'text', display: '10% chance to  inflict frozen' },
      },
      images: ['assets/snowstorm-1.webp', 'assets/snowstorm-2.webp', 'assets/snowstorm-3.webp'],
      aliases: [],
      index: 50,
    },
    {
      name: 'Soul Music',
      type: 'Secret',
      emblemOnly: false,
      passiveStats: {
        'Max CP': { value: 10.0, unit: '%', display: '10%' },
        Dodge: { value: 10.0, unit: '%', display: '10%' },
      },
      images: ['assets/soul-music-1.webp', 'assets/soul-music-2.webp', 'assets/soul-music-3.webp'],
      aliases: [],
      index: 51,
    },
    {
      name: 'Inner Light',
      type: 'Secret',
      emblemOnly: false,
      passiveStats: { Purify: { value: 10.0, unit: '%', display: '10%' } },
      images: [
        'assets/inner-light-1.webp',
        'assets/inner-light-2.webp',
        'assets/inner-light-3.webp',
      ],
      aliases: [],
      index: 52,
    },
    {
      name: 'Thunderclap',
      type: 'Secret',
      emblemOnly: false,
      passiveStats: { 'Crit chance%': { value: 10.0, unit: '%', display: '10%' } },
      images: [
        'assets/thunderclap-1.webp',
        'assets/thunderclap-2.webp',
        'assets/thunderclap-3.webp',
      ],

      aliases: [],
      index: 53,
    },
    {
      name: 'Mangekyou Sharingan',
      type: 'Secret',
      emblemOnly: false,
      passiveStats: {
        Other: {
          value: null,
          unit: 'text',
          display: '30% chance genjutsu rebound, 5% chance to copy jutsu',
        },
      },
      images: [
        'assets/mangekyou-sharingan-1.webp',
        'assets/mangekyou-sharingan-2.webp',
        'assets/mangekyou-sharingan-3.webp',
      ],
      aliases: [],
      index: 54,
    },
    {
      name: 'Eternal Black Flame',
      type: 'Secret',
      emblemOnly: false,
      passiveStats: { 'Max HP': { value: 20.0, unit: '%', display: '20%' } },
      images: [
        'assets/eternal-black-flame-1.webp',
        'assets/eternal-black-flame-2.webp',
        'assets/eternal-black-flame-3.webp',
      ],
      aliases: [],
      index: 55,
    },
    {
      name: 'Katsuryugan',
      type: 'Secret',
      emblemOnly: false,
      passiveStats: { Other: { value: null, unit: 'text', display: 'HP recover 30% dmg' } },
      images: [
        'assets/katsuryugan-1.webp',
        'assets/katsuryugan-2.webp',
        'assets/katsuryugan-3.webp',
      ],
      aliases: [],
      index: 56,
    },
    {
      name: 'Crystal Sanctuary',
      type: 'Secret',
      emblemOnly: false,
      passiveStats: {
        'Max CP': { value: 10.0, unit: '%', display: '10%' },
        'Dmg. Reduction': { value: 10.0, unit: '%', display: '10%' },
      },
      images: [
        'assets/crystal-sanctuary-1.webp',
        'assets/crystal-sanctuary-2.webp',
        'assets/crystal-sanctuary-3.webp',
      ],
      aliases: [],
      index: 57,
    },
    {
      name: 'Tremor',
      type: 'Secret',
      emblemOnly: false,
      passiveStats: { 'Dmg. Bonus': { value: 20.0, unit: '%', display: '20%' } },
      images: ['assets/tremor-1.webp', 'assets/tremor-2.webp', 'assets/tremor-3.webp'],
      aliases: [],
      index: 58,
    },
    {
      name: 'Archery',
      type: 'Secret',
      emblemOnly: false,
      passiveStats: { Accuracy: { value: 15.0, unit: '%', display: '15%' } },
      images: ['assets/archery-1.webp', 'assets/archery-2.webp', 'assets/archery-3.webp'],
      aliases: [],
      index: 59,
    },
    {
      name: 'Raijin Flash',
      type: 'Secret',
      emblemOnly: false,
      passiveStats: { Agility: { value: 15.0, unit: 'flat', display: '15' } },
      images: [
        'assets/raijin-flash-1.webp',
        'assets/raijin-flash-2.webp',
        'assets/raijin-flash-3.webp',
      ],
      aliases: [],
      index: 60,
    },
    {
      name: 'Abyssal Void',
      type: 'Secret',
      emblemOnly: false,
      passiveStats: { 'Max CP': { value: 10.0, unit: '%', display: '10%' } },
      images: [
        'assets/abyssal-void-1.webp',
        'assets/abyssal-void-2.webp',
        'assets/abyssal-void-3.webp',
      ],
      aliases: [],
      index: 61,
    },
    {
      name: 'Sunfire',
      type: 'Secret',
      emblemOnly: false,
      passiveStats: { Accuracy: { value: 25.0, unit: '%', display: '25%' } },
      images: ['assets/sunfire-1.webp', 'assets/sunfire-2.webp', 'assets/sunfire-3.webp'],
      aliases: [],
      index: 62,
    },
    {
      name: 'Stormcloud',
      type: 'Secret',
      emblemOnly: false,
      passiveStats: { 'Crit chance%': { value: 20.0, unit: '%', display: '20%' } },
      images: ['assets/stormcloud-1.webp', 'assets/stormcloud-2.webp', 'assets/stormcloud-3.webp'],
      aliases: [],
      index: 63,
    },
    {
      name: 'Snow Release',
      type: 'Secret',
      emblemOnly: false,
      passiveStats: { Other: { value: null, unit: 'text', display: 'CP recover 9% dmg taken' } },
      images: [
        'assets/snow-release-1.webp',
        'assets/snow-release-2.webp',
        'assets/snow-release-3.webp',
      ],
      aliases: [],
      index: 64,
    },
    {
      name: 'Gale Release',
      type: 'Secret',
      emblemOnly: true,
      passiveStats: {
        'Crit chance%': { value: 15.0, unit: '%', display: '15%' },
        Dodge: { value: 15.0, unit: '%', display: '15%' },
      },
      images: [
        'assets/gale-release-1.webp',
        'assets/gale-release-2.webp',
        'assets/gale-release-3.webp',
      ],
      aliases: [],
      index: 65,
    },
    {
      name: 'Puppeteering',
      type: 'Secret',
      emblemOnly: true,
      passiveStats: { Purify: { value: 12.0, unit: '%', display: '12%' } },
      images: [
        'assets/puppeteering-1.webp',
        'assets/puppeteering-2.webp',
        'assets/puppeteering-3.webp',
      ],
      aliases: [],
      index: 66,
    },
    {
      name: 'Sand Burial',
      type: 'Secret',
      emblemOnly: true,
      passiveStats: { Other: { value: null, unit: 'text', display: 'HP recover 25% CP cost' } },
      images: [
        'assets/sand-burial-1.webp',
        'assets/sand-burial-2.webp',
        'assets/sand-burial-3.webp',
      ],
      aliases: [],
      index: 67,
    },
    {
      name: "Vampire's Touch",
      type: 'Secret',
      emblemOnly: false,
      passiveStats: { Other: { value: null, unit: 'text', display: 'CP recover 10% dmg' } },
      images: [
        'assets/vampire-s-touch-1.webp',
        'assets/vampire-s-touch-2.webp',
        'assets/vampire-s-touch-3.webp',
      ],
      aliases: [],
      index: 68,
    },
    {
      name: 'Macabre Bone Pulse',
      type: 'Secret',
      emblemOnly: true,
      passiveStats: { 'Dmg. Reduction': { value: 10.0, unit: '%', display: '10%' } },
      images: [
        'assets/macabre-bone-pulse-1.webp',
        'assets/macabre-bone-pulse-2.webp',
        'assets/macabre-bone-pulse-3.webp',
      ],
      aliases: [],
      index: 69,
    },
  ],
  statColumns: [
    'Max HP',
    'Max CP',
    'Agility',
    'Crit chance%',
    'Crit dmg%',
    'Dodge',
    'Accuracy',
    'Purify',
    'Dmg. Bonus',
    'Dmg. Reduction',
    'HP regen',
    'CP regen',
    'Other',
  ],
  meta: { source: 'Ninja Saga Talents(1).xlsx', screenshotCount: 318 },
};
